version: '2'
services:
  github-ingestion:
    build: './github-ingestion'
    environment:
      API_TOKEN: $GITHUB_API_TOKEN
  pivotal-ingestion:
    build: './pivotal-ingestion'
    environment:
      API_TOKEN: $PIVOTAL_API_TOKEN
      PROJECT_IDS: $PIVOTAL_PROJECT_IDS
