version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  github-ingestion:
    build: './github-ingestion'
    environment:
      API_TOKEN: $GITHUB_API_TOKEN
    volumes:
      - github-ingestion-state:/data
  pivotal-ingestion:
    build: './pivotal-ingestion'
    environment:
      API_TOKEN: $PIVOTAL_API_TOKEN
      PROJECT_IDS: $PIVOTAL_PROJECT_IDS
volumes:
  github-ingestion-state:
