version: '2'
services:
  redis:
    image: redis:3.2.4
  github-ingestion:
    build: './github-ingestion'
    environment:
      API_TOKEN: $GITHUB_API_TOKEN
    links:
      - redis
  pivotal-ingestion:
    build: './pivotal-ingestion'
    environment:
      API_TOKEN: $PIVOTAL_API_TOKEN
      PROJECT_IDS: $PIVOTAL_PROJECT_IDS
