version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-conf:/opt/zookeeper-3.4.6/conf
      - zookeeper-data:/opt/zookeeper-3.4.6/data
  kafka:
    image: wurstmeister/kafka:0.10.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - kafka-data:/kafka
  github-ingestion:
    build: './github-ingestion'
    environment:
      API_TOKEN: $GITHUB_API_TOKEN
    volumes:
      - github-ingestion-state:/data
  consumers:
    build: './consumers'
    volumes:
      - consumer-state:/data
#   pivotal-ingestion:
#     build: './pivotal-ingestion'
#     environment:
#       API_TOKEN: $PIVOTAL_API_TOKEN
#       PROJECT_IDS: $PIVOTAL_PROJECT_IDS
volumes:
  github-ingestion-state:
  consumer-state:
  kafka-data:
  zookeeper-conf:
  zookeeper-data:
