version: '2'
services:
  kafka:
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
  sqlite:
    build: ./sqlite
    command: '/data/github-ingestion.db'
    volumes:
      - github-ingestion-state:/data
  kafka-util:
    build: ./kafka-util
    links:
      - kafka
    volumes:
      - ./kafka-util/src:/usr/src/app/src
  github-ingestion:
    command: ['yarn', 'run', 'start-dev']
    volumes:
      - ./github-ingestion/src:/usr/src/app/src
    environment:
      GITHUB_API_BASE_URL: $GITHUB_API_BASE_URL
